server:
  error:
    include-message: always
  port: 8081

chat:
  url: http://chat-system:8082
  users_url: http://chat-system:8082/users
  socket_url: ws://chat-system:8082/ws

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/zettalove
    username: dev
    password: 1234a
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    servlet:
      multipart:
        max-file-size: 8MB
        max-request-size: 8MB
