server:
  error:
    include-message: always
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/zettalove
    username: dev
    password: 1234a
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    servlet:
      multipart:
        max-file-size: 8MB
        max-request-size: 8MB
