api:
  version: 1
  title: ZettaLove REST API
  description: ZettaLove REST API

server:
  error:
    include-message: always
  port: 8081
  servlet:
    context-path: /api/v${api.version}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zettalove
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    servlet:
      multipart:
        max-file-size: 8MB
        max-request-size: 8MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ZettaKeycloak
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: zettalove-rest-api-auth
      principle-attribute: preferred_username
  admin-client:
    server-url: http://localhost:8080
    realm: ZettaKeycloak
    client-id: zettalove-rest-api-admin
    username: admin
    password: admin
    secret-key: yzVRvuhCsmuKtdSSt8NvRS0C9h9AITRA

