server:
  error:
    include-message: always
  port: 8081

chat:
  url: http://localhost:8082
  users_url: http://localhost:8082/users
  socket_url: ws://localhost:8082/ws

spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/zettalove
    username: dev
    password: 1234a
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6381
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    servlet:
      multipart:
        max-file-size: 8MB
        max-request-size: 8MB
