version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "zettalove"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile-keycloak
    environment:
      DB_VENDOR: "postgres"
      DB_ADDR: "postgres"
      DB_DATABASE: "zettalove"
      DB_USER: "postgres"
      DB_PASSWORD: "1234"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

#  spring-boot-app:
#    build: ../server  # Assuming your Spring Boot project is in the 'server' directory
#    environment:
#      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/zettalove"
#      SPRING_DATASOURCE_USERNAME: "dev"
#      SPRING_DATASOURCE_PASSWORD: "1234a"
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgres
#      - keycloak

volumes:
  postgres_data:
