# Use the official Keycloak 25.0.1 image as the base
FROM quay.io/keycloak/keycloak:25.0.1

# Set environment variables for Keycloak
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin

# Expose the Keycloak port
EXPOSE 8080

# Run Keycloak with the appropriate parameters
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
